### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by almaraze** [DataByne/uraPointOfSale#14]
As a business owner, I want to have product inventory management, so I can manage quantity of stock and to determine when and how often to reorder products.

**Comment by RyanYoak** [comment]
#57 Creates the stock table.
#58 Appropriately modifies the stock table when something is ordered.
#59 Allows the user to appropriately modify the stock directly.
#60 Allows for the user to know when stock is running low without directly checking the stock.
