### ISSUE TITLE
Sales Analytics 

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#15]
As an owner, I want to know when my sales are the highest, what factors affect sales, and possibly predict what similar weeks or days sales will be based on previous weeks.

**Comment by peterle08** [comment]
- Knowing "when my sales are the highest" or the lowest , is it a template of Business Report #22?

- Factors that affect the sales are variable, so I think it's hard to determine

- Periodic Sale revenue is also a template Business Report #22

**Comment by kyletpugh** [comment]
I agree, this is a duplicate of #22.
