### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by DataByne** [DataByne/uraPointOfSale#150]
Create an image befitting our company

**Comment by MarcoDotIO** [comment]
![bitmap-white](https://user-images.githubusercontent.com/20867620/68711200-32c89d00-0567-11ea-996c-19e090a0128a.png)
![bitmap](https://user-images.githubusercontent.com/20867620/68711201-32c89d00-0567-11ea-9030-1f30200d53c1.png)

Will add them to app/images
