### ISSUE TITLE
Customer Management

### ISSUE THREAD

**Issue by almaraze** [DataByne/uraPointOfSale#16]
As a business owner, I want to be able to log customer purchases, so I can  keep in touch with customers through marketing tools.

**Comment by RyanYoak** [comment]
#30 Makes the table that the customers who chose to identify themselves will be stored
#31 Seems like the best place to place this issue for now but may need to be moved to a different user story
#32 If we want to "stay in touch" we should be able to quickly generate a message to send to that customer
#33 The customer should have a field to enter their unique email for their order so as to identify themselves from others if they chose

**Comment by kyletpugh** [comment]
Superceded by #73. Customers should be allowed to register in addition to guest style checkout.
