### ISSUE TITLE
Employee Management

### ISSUE THREAD

**Issue by almaraze** [DataByne/uraPointOfSale#17]
As a business owner, I want to track employee hours and sales, so I can analyze who my top sales personnel are.

**Comment by RyanYoak** [comment]
You beat me to this by like 1 minute.

**Comment by almaraze** [comment]
Well I think they're a little different
Yours talks about employee account privileges.  Mine talks about just the database that stores the info for the employees.  Just leave yours up too.  I think we will use these do derive our features anyway.

**Comment by RyanYoak** [comment]
#34 We will need a table to keep track of employees we want to track

**Comment by kyletpugh** [comment]
Superceded by #73. Employees should have basic accounts like a customer but should have a linked entry in a separate table providing employee only attributes.
