### ISSUE TITLE
Create login/logout

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#23]
Create a simple page to provide an option to login. Potentially allow choice of authenticating by  GitHub, or other authentication services.

**Comment by kyletpugh** [comment]
Do you mean that we should use github as a service for authentication? Or that it should be an option in addition to the site's authentication?

**Comment by ZackBeal** [comment]
Added simple login module to the current website, no actual back end functionality created yet.Began looking into various Oauth options.
