### ISSUE TITLE
Page to Add, Edit, Remove products from the Catalog

### ISSUE THREAD

**Issue by almaraze** [DataByne/uraPointOfSale#24]
Create a page where the user can add, modify, or remove products from the product table.

Any products that are removed from the catalog should only be removed from being visible on the page but should remain on the table to be archived.

User should be able to set default attributes on this page as well.

This feature is reliant on #52

**Comment by almaraze** [comment]
[Features](https://github.com/DataByne/uraPointOfSale/issues/24)

**Comment by almaraze** [comment]
[User Story](https://github.com/DataByne/uraPointOfSale/issues/6)

**Comment by almaraze** [comment]
User story #6

**Comment by kyletpugh** [comment]
Do you think a user (with the right privilege, like the admin) should be able to recover a "deleted" product?
