### ISSUE TITLE
Testing standards

### ISSUE THREAD

**Issue by kyletpugh** [DataByne/uraPointOfSale#26]
Develop a testing methodology and documentation for how code should provide self-tests to show a feature is working for review, how to test for reviewing pull requests, and for testing milestones and releases.

**Comment by kyletpugh** [comment]
This requires that coding and documentation standards are sufficiently in place #25.

**Comment by ZackBeal** [comment]
[Very pertinent](https://github.com/marketplace/travis-ci)

**Comment by kyletpugh** [comment]
Yes, agreed. Should be free for an open source repository right? Do we need anything else besides the pre-production instance and that? Should @DataByne set that up, or you? We probably need to push this one more sprint to properly address how the testing will actually be performed though, do you agree?

**Comment by kyletpugh** [comment]
[Development Testing](https://github.com/DataByne/uraPointOfSale/wiki/Development-Resources-and-Help#development-testing)
