### ISSUE TITLE
Create Database Queries to Fill in Reports

### ISSUE THREAD

**Issue by akf98** [DataByne/uraPointOfSale#28]
Create database queries to fill in the daily reports with the relevant information. These queries don't change typically.
#22

**Comment by kyletpugh** [comment]
If a user has created a template of information for the report that is of use to that user, is everything still going to be queried, even if the report requires only a small subset of information that is available?

**Comment by akf98** [comment]
> If a user has created a template of information for the report that is of use to that user, is everything still going to be queried, even if the report requires only a small subset of information that is available?

I will give an example, let's say we want to include the sold items and their prices, the queries will always be the same i.e. SELECT statements that would generate the sold items and their types and prices. Since the template is the same, the queries will be the same, the only variable is the date of the day they will be generated.

**Comment by kyletpugh** [comment]
But there may be a complicated tree that actually entails what a product is, since there may be multiple things that you could add to each product that is also a product, or just an attribute that describes a variation of the product. So how could the queries always be the same?

**Comment by akf98** [comment]
> But there may be a complicated tree that actually entails what a product is, since there may be multiple things that you could add to each product that is also a product, or just an attribute that describes a variation of the product. So how could the queries always be the same?

Now that's an interesting issue, I think it will depend on the structure of the database that we will create. We might need to use some JOIN statements to get it envolved.

> EDIT: Remember that there is a user created template for this report as well, what is this template doing if not being used to create these queries?

Actually this is what I meant at the beginning (probably I didn't express it correctly). The user template, that is set at the beginning, would decide what is in there in the report, which is what we will find queries for. (I'm not sure if it is more clear now)

**Comment by kyletpugh** [comment]
Okay, yes, I wanted to understand if you meant that they were being generated so they wouldn't change unless the template did or whether you meant it was always the same query. It is clear.
