### ISSUE TITLE
Business Report Auto-Generation

### ISSUE THREAD

**Issue by akf98** [DataByne/uraPointOfSale#29]
We should have a button where the admins/users can generate the daily report up until the time of the generation. Taking advantage of the queries and templates we created earlier, this report should have the ability to be exported to a pdf file (using one click) so that it can be easily printable & readable.
#22

**Comment by kyletpugh** [comment]
What do you mean up until the time of the generation? That the reports are generated automatically at a specific time set by the user and there is an option to generate before that? Does this allow the report to be generated multiple times?

**Comment by akf98** [comment]
Yes. So let's say the owner at 4:00 PM decided to check out what they sold for the day, they can do that, and at the end of the day a copy of the report will be generated and sent to an email (for example).

**Comment by kyletpugh** [comment]
So can a user get the report immediately at 4PM too? Or have to wait until the scheduled time? Can the user generate multiple such reports throughout the day?

**Comment by akf98** [comment]
Yes t

> So can a user get the report immediately at 4PM too? Or have to wait until the scheduled time? Can the user generate multiple such reports throughout the day?

Yes, they can.
