### ISSUE TITLE
Create a Table for all Sales

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#31]
Create a table for all sales that includes such fields as a unique sale ID, date, time, price, the employee who sold the purchase, a unique customer ID (if they give their email, NULL otherwise), and items in order. Order the table by date.

**Comment by kyletpugh** [comment]
Should link to a customer entirely by the customer identifier, see #30, if they do not provide an email (or are not logged in or something, maybe customers can have accounts?) then the field should be NULL. How do you propose to store the items in order in this table?
