### ISSUE TITLE
Product Analytics

### ISSUE THREAD

**Issue by 4classKSU** [DataByne/uraPointOfSale#42]
We should try to implement simple analytics for each product. Basically, on any given day we will show the number of times a certain product was sold. We could add daily totals to make them weekly totals, and so on. Basically, this would help business owners see what products are being sold at the highest volume and they can adjust their shipments in accordingly.

**Comment by 4classKSU** [comment]
#15

**Comment by kyletpugh** [comment]
Superceded by #22.
