### ISSUE TITLE
Implement ability to link other products as sub-products

### ISSUE THREAD

**Issue by almaraze** [DataByne/uraPointOfSale#43]
Implement the ability to link other products as sub-products. 
The original product may have additional sub-products or attributes that are required, such as toppings on a pizza or color selection of a device.  Sub-products may have additional such requirements.

**Comment by almaraze** [comment]
[From User Story: Add, edit, or remove products in a product catalog #6](https://github.com/DataByne/uraPointOfSale/issues/6)

**Comment by almaraze** [comment]
#6

**Comment by almaraze** [comment]
#6

**Comment by kyletpugh** [comment]
How will sub-products be linked? How will the sub-products be stored, the same as products? How will the user perform this linking?

**Comment by almaraze** [comment]
This is one that I had a little trouble wrapping my mind around.  I think the simplest way would be to store all products and sub-products on a single table of products because the user story requires that all products have the ability to be sub-products as well.  The fact that something is a sub-product of something will only really matter to the user so maybe it's something that we may want to ignore on the back end and just implement on the front end.  It could be as easy as just having the user identify a product they want to be a sub-product and then just indent it under the product they want it under.   I don't know.  What do you think?

**Comment by kyletpugh** [comment]
Oh, yeah, one table for every product and to link a product to another, just use another table that has a product and sub-product and they are linked by identifiers of each product. So essentially just a pair of product ids.
