### ISSUE TITLE
Add an attributes table

### ISSUE THREAD

**Issue by almaraze** [DataByne/uraPointOfSale#44]
Add an attributes table that has relationship with products table.
this feature relies on #52

**Comment by almaraze** [comment]
#6

**Comment by kyletpugh** [comment]
How will custom  attributes be stored? How will custom attributes be created by the user? How will custom attributes be associated with a product?

**Comment by almaraze** [comment]
changed this to attributes table that has relationship with product table.  if we make the fields attributeID, attribute_name, attribute_data and they're all char(20) for example, users can then use it to add their custom attributes.  If anyone thinks there's an easier way, feel free to comment.
