### ISSUE TITLE
Bundles

### ISSUE THREAD

**Issue by rdulwort** [DataByne/uraPointOfSale#45]
As a business owner i want to be able to bundle certain products together and set an overall price for the bundle  to get customers to buy more products than what they may have originally came here for; ie. silverware, bowls and plates in a bundle set to a slightly lower price than buying them all separately.

**Comment by RyanYoak** [comment]
#61 Creates a table that lists the names and ID's of the combo deals as well as their details.
#62 Creates individual deals and their details.
#63 Is what allows for the deals to be processed and added to an order.
#64 Allows the user to create and edit deals as they see fit.
