### ISSUE TITLE
Versatility on mobile platforms 

### ISSUE THREAD

**Issue by MaidenOfTheMain** [DataByne/uraPointOfSale#53]
To keep track of inventory, customer, and employee statistics, a business manager must be able to use UraPoS outside of their business through their mobile devices (e.g., iOS) in order to have real-time statistics about the current state of their business.

https://github.com/DataByne/uraPointOfSale/issues/15

**Comment by kyletpugh** [comment]
Marcus, do not work on stuff you have not been assigned or self-assigned, also this is not a probable enhancement as we have decided to use responsive web platform entirely at this point and we do not have enough time or resources to devote to other platforms for the purposes of class.
