### ISSUE TITLE
Keep track total Sales Revenue of each period

### ISSUE THREAD

**Issue by peterle08** [DataByne/uraPointOfSale#54]
As a manager, I would like to know the total sale revenues at the end of the day, or the total sale revenues of each period such as Weekly, Monthly and quarterly.

**Comment by kyletpugh** [comment]
Could you explain how this issue is different from issue #22?

**Comment by peterle08** [comment]
They are almost the same, but there are some differences:
- Just need the total sale revenues (it’s not for any specific products or services)
- The total revenue will be categorized into Cash, Debit/Credit and Gifts.
- These informations are just numbers (No chart required) 
- With these informations, I can know difference between the total revenue on POS system (Budget) and the total revenue from Cash On Hand, Reciepts, and used Gift cards. This help to check embezzlement.

**Comment by kyletpugh** [comment]
I don't see why these things couldn't be specified in the template to generate reports? There can be more than one template used to generate a report for different data.

**Comment by peterle08** [comment]
Duplicate of #22
