### ISSUE TITLE
Product Categorization

### ISSUE THREAD

**Issue by peterle08** [DataByne/uraPointOfSale#56]
As a uraPOS user, I want products and services to be grouped by categories so that I can search them, find them or make a selection faster.

**Comment by RyanYoak** [comment]
#67 allow the basic ability to search for products.
#69 modifies the search page to give the searcher more options.
#68 lets the user have categories and have products that are in those categories,
#71 provides a way to modify those categories and what is in them.
#70 Allows the user to only view products in certain categories.
