### ISSUE TITLE
Inventory Table

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#57]
Create a table to store the inventory of the stock in the store with such fields (that may or may not include) Product name, Product ID, number in stock, time since last refilled

**Comment by kyletpugh** [comment]
I think you mean product id instead of item? Also, there may be a point where the stock is zero and having a next refill date may be necessary.

**Comment by kyletpugh** [comment]
Actually is this table needed? Would it be better to extend the product table to include these extra fields?

**Comment by RyanYoak** [comment]
This is a better Idea

**Comment by kyletpugh** [comment]
Duplicate supercession for #52.
