### ISSUE TITLE
Add, edit, or remove products in a product catalog

### ISSUE THREAD

**Issue by kyletpugh** [DataByne/uraPointOfSale#6]
Add a product name, description, and price to a product catalog. The product may have additional sub-products or attributes that are required, such as toppings on a pizza or color selection of a device. Sub-products may have additional such requirements. Products should be able to be edited, shown or hidden at a specific time or interval, or removed from the product catalog.

**Comment by almaraze** [comment]
[User Story](https://github.com/DataByne/uraPointOfSale/issues/24)

**Comment by kyletpugh** [comment]
You are close but this is multiple features. Which is why it was not directly marked with "Enhancement" tag. Please provide a better description of the issue(s) that you are linking to, i.e. just use the issue name. The ability to add, edit, or remove products with default attributes needed for cataloging is one feature. The ability to link other products as sub-products is another feature. And finally the ability to add custom attributes is another feature. We do not want to group these together or the task will be very large and unwieldy, breaking it into smaller parts that can be done after one part is working is what the objective of extracting features from user stories.

**Comment by kyletpugh** [comment]
How will products be stored? What happens when the product is removed but sale receipt(s) still link to the product id? What are the default attributes of a product?

**Comment by almaraze** [comment]
**Features**  
#24 
#55 
#44 
#52 
#43 is still incomplete.  However I added a comment at the bottom with my thoughts.  I need help with that one.
