### ISSUE TITLE
Individual Deals Tables

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#62]
Create a table with the ID pairs of Deal_ID and Product_ID

Example:
If three items, \#344, \#345, \#347 were part of a deal \#123

| Deal_ID | Product_ID |
| --- | --- |
| 123 | 344 |
| 123 | 345 |
| 123 | 347 |
| 234 | 244 |
| 234 | 344 |
| 345 | 345 |
| 345 | 347 |
| 345 | 765 |

Dependent on #61

**Comment by kyletpugh** [comment]
Creating a table for each deal is not really plausible. This should be one table that has an id pair: a deal id, and a product id. Then you would join the deal table, this table, and the product table to get the products in the bundle/deal. When products are part of a bundle/deal the product id is added into a pair entry with the deal id.

**Comment by RyanYoak** [comment]
So you're saying we need on a table with a list of deal IDs and product IDs, so if three items were part of a deal it would look
| Deal_ID  |Product_ID|
|123|344|
|123|345|
|123|347|

**Comment by kyletpugh** [comment]
Yes, I edited your comment to fix the table and to make it more obvious what I mean (I hope).
