### ISSUE TITLE
Deal Finder

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#63]
Create an object/method that looks through the deals table #61 and when it finds deals that are active (in date/time range and the user wants them to be active) joins the deals, deals list table and products table to see if all items are present for the deal to apply. If it is then it applies the negative modifier to the price as listed in the deals table in #61.

Dependent on #61 and #62

**Comment by kyletpugh** [comment]
This needs modified because #61 and #62 need modified.
