### ISSUE TITLE
Create A Pool of Layouts

### ISSUE THREAD

**Issue by akf98** [DataByne/uraPointOfSale#65]
A number of suggested pre-designed layouts should be created to give the user the ability to choose one. Each element of these layouts should have flexibility to change. In other words, a user might choose a layout but change its font, this should be doable in the simplest way. #7

**Comment by kyletpugh** [comment]
What will an pre-designed layout entail? How does the user modify this layout? What if the user wants to create their own custom layout?

**Comment by akf98** [comment]
I am trying to imagine this as the templates that appear when you open a Microsoft Word document. There are many suggestions that the software provides you, but you can still modify them or do your own. Does that make it clearer?

**Comment by kyletpugh** [comment]
No, that is obvious. You did not answer any of my questions though. How can this be accomplished?

**Comment by akf98** [comment]
Oh, I get it now. 
1) 

> What will a pre-designed layout entail?

Different layouts would contain the same components with a different view. Meaning, the list of products/product categories, the currently-being-prepared receipt .. etc. (I can go through details if this is the ambiguous part). 

2) 

> How does the user modify this layout?

There should be a button that the user can go into an editing mode through it, in which they can change the font, drop/add an element, change the positions of the elements or their size on the screen. This should also be an option when the user starts the project.

3)

>  What if the user wants to create their own custom layout?

They should be able to, we should allow them to choose certain characteristics. Meaning, they should go through a step where they choose a font, and a step where they choose what to add as elements to the screen, then they modify the positions of these elements .. etc.

**Comment by kyletpugh** [comment]
Ok, way more clear, so basically a set of drag and drop views, that can be each be customized by a set of modal dialogs that pertain to each view?

**Comment by akf98** [comment]
Exactly!
