### ISSUE TITLE
Make The Front-End Code Flexible

### ISSUE THREAD

**Issue by akf98** [DataByne/uraPointOfSale#66]
The front end code should be flexible to the different layouts available (referencing feature #65). The user should be able to switch layouts at any time for his business and this requires the front-end code to accommodate for that. #7

**Comment by kyletpugh** [comment]
I am unsure what this means so I do not even know how to respond. But does not really make sense to design something that does not work, right?

**Comment by akf98** [comment]
Wait I'm confused now. The point behind this enhancement was to divide the task into more of a graphic design task and a software development task. Does that make sense?

**Comment by kyletpugh** [comment]
But you did not explain how to do this, you just rephrased what the user story already specified.

**Comment by akf98** [comment]
> you did not explain how to do this
Yeah, you're right, it would probably need someone who's more experienced/knowledgeable about front end programming than I am to explain this aspect, I'm kinda a noob in that area lol.

> you just rephrased what the user story already specified
Looking at it again, you probably have a point. I think the other enhancement for the same story is detailed enough now so we probably can drop this one.

**Comment by kyletpugh** [comment]
I agree, this is not valid. I have marked as such.
