### ISSUE TITLE
Layout customization

### ISSUE THREAD

**Issue by MaidenOfTheMain** [DataByne/uraPointOfSale#7]
As a business owner who's potentially willing to invest time and assets into UraPOS, I want to have the ability to customize how the interface looks so that the product fits in more with the theme of my business.

So in short, we should add the ability to customize how UraPOS looks in terms of interface layout, backgrounds, fonts, etc. Businesses tend to favor products that fit with the theme of their company (e.g., color scheme, layout, font choices, etc.).

**Comment by MaidenOfTheMain** [comment]
Also, regarding the question if this would be a super-class of the ability to add and remove items, my response would be, "No." Mainly this is for the aesthetic changes that do not affect how the end product works. More so again regarding fitting the needs of the consumers who are wanting such a product.

**Comment by akf98** [comment]
#65
