### ISSUE TITLE
Create Payment Table

### ISSUE THREAD

**Issue by peterle08** [DataByne/uraPointOfSale#76]
This table is store pmt_ID, Sales_ID, debit_amount, cash_amount, gift_amount, total_payment
- Sale_ID will link from sales table #47

**Comment by peterle08** [comment]
#20

**Comment by kyletpugh** [comment]
This is insufficient, how do you know which payment went to which sale? Also what about splitting payments across multiple methods as #20 requires?

**Comment by kyletpugh** [comment]
Also the date should be on the sale already, so it's unnecessary in this table.
