### ISSUE TITLE
Decide on web framework and database for project

### ISSUE THREAD

**Issue by kyletpugh** [DataByne/uraPointOfSale#9]
Decide which framework(s) we want to use for development.

**Comment by kyletpugh** [comment]
I believe we have already decided on python 3 for back end, and HTML/CSS/JavaScript for front end. We  just need to decide on a front end framework (or to not use one, although that would probably be a mistake) and the back end database.

**Comment by ZackBeal** [comment]
I think PostgreSQL would be preferred for the database.
I'm impartial to either Angular or Bootstrap for the front end.
Angular would most likely be easier to implement though.

**Comment by kyletpugh** [comment]
Angular sounds good. PostgreSQL sounds good. I assume we will use psycopg2 then as well? Then that should sufficiently answer this issue once you get all that installed/running on the server.

**Comment by kyletpugh** [comment]
This needs completed before #25 can be completed.

**Comment by kyletpugh** [comment]
Unless someone has something else to add to this issue, then it seems to be resolved. This should be closed once @ZackBeal has Python 3, PostgreSQL, and psycopg2 installed on the server and Angular is deployed to the repository.

**Comment by ZackBeal** [comment]
Created test host and installed all dependencies (Python 3, PostgreSQL, and psycopg2). Prod and test are now 1:1. I'll reach out to those with credentials and access information.

**Comment by kyletpugh** [comment]
This is completed then? We can talk about deploying Angular with coding standards as to how we want to store the structure of the code base
